version: "3.8"

services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
      # - "443:443"
    depends_on:
      - appli
  appli:
    container_name: sso-frontend
    image: sso-frontend
    build:
      context: .
    
    volumes:
      - .:/appli:rw
    ports:
      - 3000:3000
    command: >
      sh -c "npm start"
    env_file:
      - .env
    restart: on-failure